name: Actions workflow

on:
  push:
  pull_request:

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
          echo 1. $GITHUB_SHA
          echo 2. $GITHUB_REPOSITORY
          echo 3. $GITHUB_WORKSPACE
          echo 4. "${{ github.token }}"
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -a
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Mohsen
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
