name: shell commands

on: [push]

jobs:
  run-shell-command-1:
    runs-on: ubuntu-latest
    needs: ["run-shell-command-2"]
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
          pwd
      - name: python command processor
        shell: python
        run: |
          import platform 
          print(platform.processor())
  
  run-shell-command-2:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string2
        run: echo "hello world2"
      - name: multiline script
        run: |
          node -v
          npm -v
          pwd
      - name: python command system
        shell: python
        run: |
          import platform 
          print(platform.system())
