name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world2"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: get location
        run: |
          ls
